### ISSUE TITLE
Application wont start in Windows

### ISSUE THREAD

**Issue by louia** [lbormann/darts-hub#1]
My application don't start ai the initial boot : 
![image](https://github.com/lbormann/autodarts-desktop/assets/33846211/581a056d-7c46-4fe6-9249-79be81a8020f)

And when I try to boot it again I have this message : 
![image](https://github.com/lbormann/autodarts-desktop/assets/33846211/db27a395-df2d-41df-80b5-b199b30b4c56)

I'm on windows, latest version (0.8.29)

**Comment by lbormann** [comment]
Did you download right version for your specific os? 
Moreover did you extract the download-file before you start? 
Which specific os do you run? 
How can I reproduce this behavior?

**Comment by louia** [comment]
I dowloaded the wrong version for my OS.... thank you anyway
