### ISSUE TITLE
Deactivate automatic updates and trigger them manually

### ISSUE THREAD

**Issue by Raabi91** [lbormann/darts-hub#5]
would it be possible in future to deactivate the automatic updates and carry out update checks manually if necessary?

The background is that the host does not run permanently and is of course updated when booting. But if you are not on site as a supervisor, the other games (family) have to play on the new version, which you have now seen with the 0.23.0, which was worse at first.

that's why i would like to be able to start the updates manually if i want to

**Comment by lbormann** [comment]
you can deny add updates any time. if you wish to stay on specific app-version; ie. autodarts-client, just follow the instructions in README (my_version)-feature. That's it.
